name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Run daily at 5:00 AM

jobs:
  data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Look for new bulletines
        run: jupyter nbconvert --to notebook --execute "notebooks/1_General_4_Weekly_scrape.ipynb"

      - name: Clean bulletines
        run: jupyter nbconvert --to notebook --execute "notebooks/1_General_3_Bulletines_clean.ipynb"

      - name: Search for updated institutes' data
        run: jupyter nbconvert --to notebook --execute "notebooks/2_Institutes_2_Weekly_scrape.ipynb"        

      - name: Analyzing the data data
        run: jupyter nbconvert --to notebook --execute "notebooks/3_Analysis.ipynb"
        
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Automated data processing"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
