name: weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON' # Run weekly

jobs:
  data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Scrape institutes info
        run: jupyter nbconvert --to notebook --execute "notebooks/1_scraper_institutes_info.ipynb"

      - name: Scrape institutes data
        run: jupyter nbconvert --to notebook --execute "notebooks/2_scraper_institutes_data.ipynb"

      - name: Analyze data
        run: jupyter nbconvert --to notebook --execute "notebooks/3_analysis.ipynb"
        
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Automated data processing"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
